
#ifndef LOAD_CELL_DOUT_PIN
#define LOAD_CELL_DOUT_PIN 18
#endif

#ifndef LOAD_CELL_SCK_PIN
#define LOAD_CELL_SCK_PIN 19
#endif

#ifndef LOAD_CELL_XTAL_PIN
#define LOAD_CELL_XTAL_PIN 5
#endif

#ifndef LOAD_CELL_XTAL_FREQ
#define LOAD_CELL_XTAL_FREQ 20000000
#endif

#ifndef LOAD_CELL_XTAL_CHANNEL
#define LOAD_CELL_XTAL_CHANNEL 0
#endif

#ifndef LOAD_CELL_XTAL_ENABLE_PIN
#define LOAD_CELL_XTAL_ENABLE_PIN 17
#endif

#ifndef BATTERY_LEVEL_PIN
#define BATTERY_LEVEL_PIN 4
#endif

#ifndef BATTERY_LEVEL_MAX_VALUE_ADC
#define BATTERY_LEVEL_MAX_VALUE_ADC 2786
#endif

#ifndef BATTERY_LEVEL_MIN_VALUE_ADC
#define BATTERY_LEVEL_MIN_VALUE_ADC 1725
#endif

#ifndef BATTERY_LEVEL_CHECK_INTERVAL_MILLIS
#define BATTERY_LEVEL_CHECK_INTERVAL_MILLIS 2000
#endif
