
#ifndef LOAD_CELL_DOUT_PIN
#define LOAD_CELL_DOUT_PIN 18
#endif

#ifndef LOAD_CELL_SCK_PIN
#define LOAD_CELL_SCK_PIN 19
#endif

#ifndef LOAD_CELL_XTAL_PIN
#define LOAD_CELL_XTAL_PIN 5
#endif

#ifndef LOAD_CELL_XTAL_FREQ
#define LOAD_CELL_XTAL_FREQ 20000000
#endif

#ifndef LOAD_CELL_XTAL_CHANNEL
#define LOAD_CELL_XTAL_CHANNEL 0
#endif

#ifndef LOAD_CELL_XTAL_ENABLE_PIN
#define LOAD_CELL_XTAL_ENABLE_PIN 17
#endif
